### PR TITLE
Add Create file action for creating JTE templates in intellij

### PR DESCRIPTION
**Pull request by barthr**
Add functionality for creating a jte template file (see screenshot)

image

### CODE REVIEW

**Comment by barthr** [comment]
This PR implements #17

**Comment by casid** [comment]
Oh nice, thank you for your contribution!

One little nitpick, jte is written lowercase, it would be nice for the label to be "jte Template".

Are you adding .kte support in this PR as well? Then I'll wait with the merge.

**Comment by barthr** [comment]
Sounds good, I will have time to do this tomorrow.

**Comment by casid** [comment]
Thanks for your contribution, I'll add the kte template on the main branch :-)

**Comment by barthr** [comment]
Sorry for my late response, I forgot about this and then went on vacation :sweat_smile:

**Comment by casid** [comment]
No worries! You already did all the hard parts, so there wasn't much left to do. Hope you had a great vacation :-)

**Pull request merged**
